### ISSUE TITLE
IOS 6 safari webaudio

### ISSUE THREAD

**Issue by rdzah** [jeromeetienne/webaudio.js#14] opened 2012-09-21 21:56 UTC
Hi, on safari 6, ios6 (ipad/iphone) & osx lion, none of the webaudio.js examples work.
All webinspector gives me is "unable to load sounds/techno.mp3"; none of the jsfx locally generated examples work either, both on github pages & local git clone.
It can playback the http://jeromeetienne.github.com/webaudio.js/examples/sounds/techno.mp3 file directly however.

FYI, this webaudio demo works on ios6:
http://jlongster.com/2012/09/12/web-apps.html
http://jlongster.com/s/touch.html
https://gist.github.com/3701232
Any hints? Thanks, chaining apis rock.

**Comment by jeromeetienne** [comment] 2012-09-21 22:59
does it provide a line number ?

**Comment by rdzah** [comment] 2012-09-21 23:22
line 536 of webaudio.js on github pages, 603 on local git clone  
console.warn("unable to load sound "+url);

**Comment by jeromeetienne** [comment] 2012-09-22 00:43
ok so 
- the line is here https://github.com/jeromeetienne/webaudio.js/blob/master/src/webaudio.sound.js#L291

```
    this._loadAndDecodeSound(url, function(buffer){
        this._source.buffer = buffer;
        callback && callback(this);
    }.bind(this), function(){
        console.warn("unable to load sound "+url);
    });
```
- it is called from here https://github.com/jeromeetienne/webaudio.js/blob/master/src/webaudio.sound.js#L310

```
        context.decodeAudioData(request.response, function(buffer) {
            onLoad && onLoad(buffer);
        }, function(){
            onError && onError();
        });
```

So i think the question is : _how come decodeAudioData fails_

i will try to reproduce

**Comment by jeromeetienne** [comment] 2012-09-22 00:44
have you tried to test if another mp3, one of those from the examples you got working

**Comment by jeromeetienne** [comment] 2012-09-22 00:59
replacing techno.mp3 by eatpill.mp3 or perfume.mp3 works

so techno.mp3 isnt loved by apple browser. seems related to the file content more than the api

**Comment by jeromeetienne** [comment] 2012-09-22 01:01
http://127.0.0.1:8000/examples/jsfx-manual/ here jsfx works
http://127.0.0.1:8000/examples/jsfx/ here too

all that tested in safari6

ok so it is clearly techno.mp3 which got issue with mp3decoder of apple. closing

**Comment by rdzah** [comment] 2012-09-22 01:23
The other mp3s & jsfx examples do work on mac desktop osx safari 6, but ipad/iphone ios6 mobile safari still play no sound no matter which mp3 or jsfx used.

**Comment by jeromeetienne** [comment] 2012-09-22 01:51
well i cant reproduce the issue unfortunatly

**Comment by jeromeetienne** [comment] 2012-09-22 01:56
maybe ios6 is buggy on some part of the nodechain... after all it is in beta

maybe it is a different default value

as i dont have ios6 i cant do much

**Comment by rdzah** [comment] 2012-09-22 02:19
Ok, I'll keep messing with it; maybe the xcode ios simulator could show it somehow?  IOS6 is production now though, 15% of devices upgraded within 24 hours of release...

**Comment by jeromeetienne** [comment] 2012-09-22 08:48
so there is a working example from the blog post, and a case which fails.

The point is to look at what is different between the 2... the only thing i can think of is the node chain.

**Comment by rdzah** [comment] 2012-09-22 17:41
hey, so not yet sure how to examine the nodechain, but here are some more data points:
io6 webaudio working links:
http://www.html5rocks.com/en/tutorials/webaudio/games/
http://chromium.googlecode.com/svn/trunk/samples/audio/index.html
http://chromium.googlecode.com/svn/trunk/samples/audio/shiny-drum-machine.html
http://chromium.googlecode.com/svn/trunk/samples/audio/convolution-effects.html
http://www.htmlfivewow.com/demos/audio-visualizer/index.html
http://static.echonest.com/BohemianRhapsichord/index.html

not working:
http://www.html5rocks.com/en/tutorials/webaudio/intro/
http://updates.html5rocks.com/2012/02/HTML5-audio-and-the-Web-Audio-API-are-BFFs
http://chromium.googlecode.com/svn/trunk/samples/audio/box2d-js/box2d-audio.html
http://aikelab.net/websynth/

I thought it was interesting that the demos from the first html5rocks webaudio tutorial (intro) fail on ios6, but the ones from the second (games) work. Perhaps the spec changed enough that chrome still supports the old code but ios6 is rigid?

One other ios6 error some of the webaudio.js demos complain about is not supporting the page visibility api:
“Assertion failed: Page Visibility API unsupported” webaudio.js, lines 170, 176 (gh pages)

**Comment by jeromeetienne** [comment] 2012-09-22 18:11
- pagevisibility stuff should not matter. this is only to mute the sound when the tab isnt visible.

**Comment by jeromeetienne** [comment] 2012-09-22 18:25
- btw i dont think there is any change in the api. but it does give an indication on where to look
- try to make http://www.html5rocks.com/en/tutorials/webaudio/intro/ works
- it is the simplest one. 

### possible path
- see that /games makes differently 
- go toward this and see when you get the sound

**Comment by rdzah** [comment] 2012-09-22 20:47
Ok so http://www.html5rocks.com/en/tutorials/webaudio/intro/ & http://www.html5rocks.com/en/tutorials/webaudio/games/ _both_ work; they require giving the page awhile to download all the sounds first or fail with type & buffer length errors. Sorry, thought we were on to something there.

The other ones that failed before still fail now, no useful errors other than "cannot play audio file".

**Closed as completed** 2013-03-04 02:28 UTC

**Comment by karneaud** [comment] 2014-12-26 18:50
Hey have you found out why it fails on iOS Safari? I am also trying it using the pulse2d.html. using and onclick event due to the iOS audio bug but no go....what gives?

**Comment by karneaud** [comment] 2014-12-26 19:27
think I know why.... http://stackoverflow.com/questions/10365335/decodeaudiodata-returning-a-null-error
